### PR TITLE
[W09H01] Add tests for `PinguTrip.onTheWay` (task 6)

### PR DESCRIPTION
**Pull request by nilsreichardt**
Add two tests:

* Point is on the way
* Point is not on the way

### CODE REVIEW

**Review by Benn1x — APPROVED** [review]
LGTM but i would add another test with several elements in the stream

**Comment by nilsreichardt** [comment]
> LGTM but i would add another test with several elements in the stream

Are there cases where these tests are passing but the Artemis tests not? For the H01 tasks there are no hidden tests so when the public tests are passing, is everything fine.

**Comment by Benn1x** [comment]
I self had the issue that it work with an 2 element Stream but not with a bigger stream

**Comment by nilsreichardt** [comment]
> I self had the issue that it worked with an 2 element Stream but not with a bigger stream

But have you passed the Artemis tests with your first implementation?

**Comment by Benn1x** [comment]
No only after i discovered the bug and fixed the bug it passed the tests

**Comment by nilsreichardt** [comment]
> No only after i discovered the bug and fixed the bug it passed the tests

Ok, thanks for the feedback. Then I will add another test 👍

**Review by MaximilianAnzinger — APPROVED** [review]

**Comment by nilsreichardt** [comment]
@Benn1x I have added another test in https://github.com/MaximilianAnzinger/pgdp2223-tests/pull/214/commits/846398c0762f92babb75f50dd11e833b90a72e16 👍

**Review by Benn1x — APPROVED** [review]
LGTM

**Pull request merged**
