### PR TITLE
Dominik Gleissner added two new tests

### PR DESCRIPTION
**Pull request by DominikGleissner**
Dominik Gleissner Tests für W04H02 und W04H03

### CODE REVIEW

**Review by nilsreichardt — CHANGES_REQUESTED** [review]
Hey @DominikGleissner 👋 Thanks for opening a PR!

This PR contains the tests for multiple PRs. We try to avoid creating a PR with tests for more than one task. So could you split this PR into multiple PRs (for every task a PR)?

And use the name of the homework as prefix like: "[W04H01] ...".

If need any help with that, let me know.

Thanks <3

**Comment by ipadmini22** [comment]
Further, couple of your tests seem not to correlate with the exercise: https://zulip.in.tum.de/#narrow/stream/1450-PGdP-W04H02/topic/Sinnvolle.20Indizes/near/793606

**Comment by DominikGleissner** [comment]
> Further, couple of your tests seem not to correlate with the exercise: https://zulip.in.tum.de/#narrow/stream/1450-PGdP-W04H02/topic/Sinnvolle.20Indizes/near/793606

Yes there you are right. My test contain some edgecases that were garantueed not be tested.. but to be safe, I made my code safe even for those cases, and so I included some tests for those cases

**Comment by ipadmini22** [comment]
Ok, I agree with that, since there is quite some doubt how serious that response was.
Though, Nils already added some tests in that direction and your PR even contains things for W05 now, that is not how it should be. Also you change quite a lot of the naming structure. I would suggest we remove this PR for now... In the future, it would be great if you keep package naming etc. as in the existing structure and create PRs only for one task at a time with the given naming structure.
And problems with that?

**Comment by DominikGleissner** [comment]
> Ok, I agree with that, since there is quite some doubt how serious that response was. Though, Nils already added some tests in that direction and your PR even contains things for W05 now, that is not how it should be. Also you change quite a lot of the naming structure. I would suggest we remove this PR for now... In the future, it would be great if you keep package naming etc. as in the existing structure and create PRs only for one task at a time with the given naming structure. And problems with that?

Yes, I did not mention to do such a pull request. I wanted to commit every test or class for a test by its own, but I'm new to git and really do not have any idea, how that would work correctly... since the tutors gave us no introduction to git apart from the readme file, it's quite hard to learn this. But nevertheless I'm fine with removing this...

**Comment by nilsreichardt** [comment]
I think we can close the PR because this PR adds only tests for W04 and this homework already completed.

**Pull request closed without merging**
