### PR TITLE
[W07H02] replace line separators for better compatibility

### LINKED ISSUE #145: [W07H02] Fix linebreaks
@julian-hartl Mehrere Leute hatten jetzt Probleme mit den Line endings, weil Windows \r\n statt normalem \n nutzt.
Tools wie IntelliJ ersetzen das, auch auf Windows, dann failt aber System.lineSeparator(). Deswegen Vorschlag:
Im output alle \r\n durch \n ersetzen und expected mit \n schreiben.

### PR DESCRIPTION
**Pull request by felixhauptmann**
Closes #145

### CODE REVIEW

**Comment by Friendly-Banana** [comment]
LGTM

**Review by Friendly-Banana — APPROVED** [review]
LGTM

**Comment by felixhauptmann** [comment]
@nilsreichardt do your thing :)

**Review by nilsreichardt — APPROVED** [review]
LGTM

**Review by MaximilianAnzinger — COMMENTED** [review]
[🐧](https://emojipedia.org/penguin/)

**Pull request merged**
