### PR TITLE
[W10H03] Added tests for amount of calls of next()

### PR DESCRIPTION
**Pull request by 0xYelshayeb**
Added 3 Tests in InfiniteTreeTest.java to check:

1- Whether the code stops immediately after optimizable.process() return true.
2- Whether the code works correctly after 2 calls without creating a new InfiniteTree.
3- Whether the code exits if from is null.

### CODE REVIEW

**Comment by 0xYelshayeb** [comment]
Thank you for @hmelder for collaborating and implementing the modifiedIterator.

**Review by hmelder — APPROVED** [review]

**Review by hmelder — APPROVED** [review]

**Comment by DominikGleissner** [comment]
First of all, big thanks for the tests!
I get other values. For all other tests my code finds the correct values, but for this one two tests fail:
Find should work for 2 consecutive calls:
Expected :4950
Actual   :7418
and
Find should stop immediately if Optimizable returns true:
Expected :2475
Actual   :3709
So I wonder whether my implementation is wrong or the expeceted values are not quite correct.
Are you 100% sure, these values are correct?
Thanks for checking!

**Comment by 0xYelshayeb** [comment]
> First of all, big thanks for the tests!
> I get other values. For all other tests my code finds the correct values, but for this one two tests fail:
> Find should work for 2 consecutive calls:
> Expected :4950
> Actual :7418
> and
> Find should stop immediately if Optimizable returns true:
> Expected :2475
> Actual :3709
> So I wonder whether my implementation is wrong or the expeceted values are not quite correct.
> Are you 100% sure, these values are correct?
> Thanks for checking!

Well it seems like you need exactly 1.5 times the amount of next() calls than the optimal solution does. Probably somewhere in your approach there are still nodes being checked even though optimizable.process() returned true, which should according to the exercise terminate the search immediately.

**Comment by DominikGleissner** [comment]
Yes my implementation was just not efficient enough! Great test! I think it would be ready to merge

**Review by DominikGleissner — APPROVED** [review]

**Review by Anatoly03 — APPROVED** [review]
Thank you!

**Comment by 0xYelshayeb** [comment]
@nilsreichardt 3 approvals. Should be ready to merge!

**Pull request merged**
