### PR TITLE
[W09H02] Add template

### PR DESCRIPTION
**Pull request by julian-hartl**
- Added basic structure for tests for Week 9 Exercise 2
- It includes a class to store json strings and a class that stores the parsed json strings
- For an example you can take a look at tests for exercise 1

### CODE REVIEW

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by Anatoly03 — CHANGES_REQUESTED** [review]
don't edit w07h03 code in w09h02 labeled pr, remove this commit

**Comment by hmelder** [comment]
Yea you would have to revert you branch and not delete the code.

**Comment by hmelder** [comment]
Then a push reset-hard to origin (if you want to keep PGdP-Test-Authors-22-23:add-template-for-w09h02)

**Comment by hmelder** [comment]
I've reduced the template size a bit :)

**Review by Anatoly03 — APPROVED** [review]

**Comment by MaximilianAnzinger** [comment]
@hmelder so I can close the PR?

**Comment by hmelder** [comment]
> @hmelder so I can close the PR?

If @julian-hartl signs of on it then yes :)

**Comment by hmelder** [comment]
w09h02 tests are currently stalled because of a lacking template.

**Pull request closed without merging**
