### PR TITLE
[W09H03] Remove unnecessary tests and moved the decoded string of the `noot.mp4` video into a serparate file

### PR DESCRIPTION
**Pull request by Friendly-Banana**
made outputting files optional

assertions now show what error happened

removed unnecessary tests for
- null: see FAQ, not tested
- crop and limit parameters <= 0: see https://zulip.in.tum.de/#narrow/stream/1505-PGdP-W09H03/topic/.E2.9C.94.20crop.20invalide.20parameter/near/866996, program can do anything

those tests serve no purpose as they can't get points but confuse users (Why are not all tests passing?)

### CODE REVIEW

**Comment by DominikGleissner** [comment]
First of all: Thank you for the huge work! Great job. Again, I'm sorry for this horrible code style.
I think by setting the String shouldBe into { ... } the compiler does not accept the test because you declare the variable shouldBe within the brackets and so to exectute assertEquals(shouldBe, ...) we have to declare the variable outside the brackets.

**Comment by Friendly-Banana** [comment]
Set the statements using shouldBe into the brackets too, that should fix it.
Please don't merge yet:
As @julian-hartl suggested in #196 that file needs to be split. Intellij couldn't even detect the bracket error cause the file is too large.
Also we need more helper methods.

**Comment by DominikGleissner** [comment]
I think it is quite ready to merge although there is still potential for improvements regarding the style. But I personally think that the most important fact is that all test work perfectly and test all the things they should test. And having in mind that the deadline is this sunday, I think the tests should be merged soon.

**Review by DominikGleissner — APPROVED** [review]

**Comment by nilsreichardt** [comment]
@Friendly-Banana I had still some compiler errors with the bracket solution. Therefore, I have moved the big string variable (`shouldBe`) in a separate file. This saves us +1.200 lines in the `DGTest.java`.

Additionally, I removed the `import static pgdp.filter.VideoContainer.IllegalVideoFormatException;` import because that also caused a compiler error.

> Please don't merge yet:
> As @julian-hartl suggested in https://github.com/MaximilianAnzinger/pgdp2223-tests/pull/196 that file needs to be split. Intellij couldn't even detect the bracket error cause the file is too large.

We should try to make the smallest PRs as possible because the increases readability for reviewers and has a bunch of more advantages. I strongly agree that we split the subtasks into separate files. However, we do this in a separate PR.

If everything is okay, I can merge this PR 👍

**Comment by Friendly-Banana** [comment]
Ok then, merge the PR.

**Review by MaximilianAnzinger — COMMENTED** [review]
[🐧](https://emojipedia.org/penguin/)

**Pull request merged**
