### PR TITLE
[W08H03] Fixed performance

### PR DESCRIPTION
**Pull request by blubsbuar**
`Collections.sort` is getting called unnecessarily. This PR fixes the unnecessary call and improves the performance of the tests.

### CODE REVIEW

**Review by nilsreichardt — COMMENTED** [review]
Could you add to the PR description what the problem was?

**Review by HendrikHuebner — APPROVED** [review]
LGTM

**Comment by HendrikHuebner** [comment]
> Could you add to the PR description what the problem was?

Collections.sort is getting called unnecessarily, which is not _really_ an issue but now that someone took the time to fix it I don't see a reason not to merge this.

**Comment by nilsreichardt** [comment]
> Collections.sort is getting called unnecessarily, which is not really an issue but now that someone took the time to fix it I don't see a reason not to merge this.

Yes, the fix is great 👍 But it's easier for other people to read the PR description (like the sentence you wrote) instead of reading the code

**Comment by nilsreichardt** [comment]
> Could you add to the PR description what the problem was?

I have already updated the PR description 👍

**Review by nilsreichardt — APPROVED** [review]
LGTM

**Review by MaximilianAnzinger — COMMENTED** [review]
🐧

**Pull request merged**
