### PR TITLE
[*] Add very important badge

### PR DESCRIPTION
**Pull request by Garfield100**
I'm not sure why it says 17 commits. The actually relevant ones were already merged some time ago.
According to the changes it is only in the readme as it should be

### CODE REVIEW

**Comment by hmelder** [comment]
You want to merge your current main into upstream main. I would recommend using a separate branch for each delegated PR and not merge upstream main into this branch (or at least be careful about it).

**Comment by hmelder** [comment]
E.g.

1. `git checkout -b add_important_batch`
2. Work on some stuff (add, commit, push) to your fork
3. Open a PR from add_important_branch to upstream main.

**Comment by Garfield100** [comment]
> You want to merge your current main into upstream main. I would recommend using a separate branch for each delegated PR and not merge upstream main into this branch (or at least be careful about it).

Good points, I'll do that next time.
It's still weird that these commits show up here when they are obviously already in the repo

**Comment by hmelder** [comment]
> Good points, I'll do that next time. It's still weird that these commits show up here when they are obviously already in the repo

The thing is that Git was technically not made for smth like "Pull requests". This was invented by Github. Git was invented to track development of the Linux kernel specifically. Linux does not have a central repository. Releases are issued by either Linus or Greg. Not a direct answer to the problem, but always keep this in mind :)

**Comment by nilsreichardt** [comment]
As long as the changes are correct, is everything fine because you squash the commits into one commit 👍

**Review by nilsreichardt — APPROVED** [review]
LGTM

**Pull request merged**
