### PR TITLE
[W07H03] extended hamster,wolf test with death

### PR DESCRIPTION
**Pull request by ipadmini22**
Essentially checked that the both wolfs will die within spec. For this reason, the existing `hamsterEatsPlantWolfEatsHamster` was extended to include extinction.

### CODE REVIEW

**Review by Friendly-Banana — APPROVED** [review]
LGTM, feel free to also add new tests

**Comment by ipadmini22** [comment]
> LGTM, feel free to also add new tests
Yeah, felt useless in this case, as it fit well into the existing one.

**Comment by nilsreichardt** [comment]
@ipadmini22 Can you resolve the conflict in `SimulationTest.java`? If you need any help with, just DM me 👍

**Comment by ipadmini22** [comment]
@nilsreichardt done, was due to someone else renaming the tests :D

**Pull request merged**
