### PR TITLE
[W09H02] additional tests averageDelayByHour

### PR DESCRIPTION
**Pull request by JumpSneak**
Additional tests for averageDelayByHour(...) with delays being < 1h and delays being >= 1h

### CODE REVIEW

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by nilsreichardt — CHANGES_REQUESTED** [review]
Hey @JumpSneak 👋 Thanks for your PR! Could you put your tests into the existing `AverageDelayByHourTest.java` file?

**Comment by felixhauptmann** [comment]
@nilsreichardt let's close this one as well

**Comment by felixhauptmann** [comment]
> @nilsreichardt let's close this one as well

In my opinion we should close all w09 PRs since they won't be of any real use and were kind of inactive anyways

**Comment by nilsreichardt** [comment]
Closing because the deadline of the task is over.

**Pull request closed without merging**
