### PR TITLE
[W04H02] remove/disable incorrect tests

### LINKED ISSUE #61: [W04H02] Merge order test does not work at all
@simonsmd please rewrite or revert [`mergeOrder`](https://github.com/MaximilianAnzinger/pgdp2223-tests/blob/main/w04h02/test/pgdp/megamerge/MergeRecursiveTest.java#L123-L205)

### PR DESCRIPTION
**Pull request by simonsmd**
- removes the `mergeOrder` test for the recursive `merge` method because it is [irrelevant](https://zulip.in.tum.de/#narrow/stream/1450-PGdP-W04H02/topic/Reihenfolge/near/790955)
- disables the `arraySplit` test for the `megaMergeSort` method because it doesn't work if helper methods are used (#62)
- resolves #61 

The `arraySplit` test should be updated to test as described [here](https://zulip.in.tum.de/#narrow/stream/1450-PGdP-W04H02/topic/wrong.20split/near/791290)

### CODE REVIEW

**Review by nilsreichardt — COMMENTED** [review]
Is this PR still needed?

**Comment by simonsmd** [comment]
The test currently doesn't work if helper methods are used and checks the splits using a different method than the one described [here](https://zulip.in.tum.de/#narrow/stream/1450-PGdP-W04H02/topic/wrong.20split/near/791290). I think it would be better to disable it until these changes are implemented.

**Review by nilsreichardt — APPROVED** [review]
LGTM

**Comment by nilsreichardt** [comment]
@simonsmd I think deleting the tests is even better because otherwise it's confusing why the test is disabled and because of Git we still have the test. If we need the code again, we can look in the Git history.

**Pull request merged**
